version: 2

jobs:
  build:
    docker:
        image: circleci/python:3.7.7

    working_directory: ~/repo
    
    steps:
        checkout

        restore_cache:
            keys:
                v1-dependencies-{{ checksum "requirements.txt" }}
                v1-dependencies-

        run:
            name: install dependencies
            command: |
                python3 -m venv venv
                . venv/bin/activate
                make install

            save_cache:
                paths:
                    ./venv
                key: v1-dependencies-{{ checksum "requirements.txt" }}

            lint:
                name: run lint
                command: |
                    . venv/bin/activate
                    make lint
            test:
                name: run tests
                command: |
                    . venv/bin/activate
                    make test
